config/routes.rb
Rails.application.routes.draw do
  root to: "customers#index"
  resources :customers
  resources :services

  devise_for :users, controllers: { registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    passwords: "users/passwords" }

  # get '/users/sign_out' => 'devise/sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :services_customers, dependent: :nullify
  has_many :services, through: :services_customers, dependent: :nullify
  accepts_nested_attributes_for :services_customers
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :new, :create, :update]
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.where(user_id: current_user.id)
    # binding.pry
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @category = Category.find(@customer.category_id)
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = current_user.customers.new(customer_params)
    respond_to do |format|
      ActiveRecord::Base.transaction do
        if @customer.save
          if service_params == ["0"]
            ServicesCustomer.create!(customer_id: nil, service_id: nil)
          else
            service_params["service_id"].each do |i|
              ServicesCustomer.create!(customer_id: @customer.id, service_id: i.to_i)
            end
          end
          format.html { redirect_to @customer, notice: "Customer was successfully created." }
          format.json { render :show, status: :created, location: @customer }
        else
          format.html { render :new }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy!
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:user_id, :category_id, :name, :age, :birthday, :kaigodo, :medical_history, :discription, :image)
    end

    def service_params
      nil_var = params["service_customer"]
      if nil_var.nil?
        ["0"]
      else
        params.require(:service_customer).permit(service_id: [])
      end
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

    <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: "選択してください" %>
    </div>

    <div class="field">
    <%= fields_for :service_customer, (@service_customer) do |sc| %>
      <%= sc.label :service_id %>
      <%= sc.collection_check_boxes :service_id, Service.all, :id, :name, include_hidden: false  %>
    <% end %>
    </div>


  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select(:birthday, start_year:DateTime.now.year, end_year:1900, date_separator:'/')%>
  </div>

  <div class="field">
    <%= form.label :kaigodo %>
    <%= form.number_field :kaigodo, in: 1..5 %>
  </div>

  <div class="field">
    <%= form.label :medical_history %>
    <%= form.text_area :medical_history %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_area :discription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>
<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p><%= "#{current_user.name}のお客様一覧"%></p>
<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p><%= link_to 'Customer を追加', new_customer_path %></p>


<p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %> </p><!-- ログアウトをする -->

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>
<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<% if @customer.image?%>
  <%=image_tag @customer.image.url %>
<% end %>
</p>


<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= (Date.today.strftime('%Y%m%d').to_i - @customer.birthday.strftime('%Y%m%d').to_i) / 10000 %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @customer.birthday %>
</p>

<p>
  <strong>Kaigodo:</strong>
  <%= @customer.kaigodo %>
</p>

<p>
  <strong>Medical history:</strong>
  <%= @customer.medical_history %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @customer.discription %>
</p>

<p>
  <strong>Servise in use:</strong>
  <% if @customer.services_customers.exists?%>
    <% @customer.services_customers.each do |sc| %>
      <%= sc.service.name%>
  <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>